/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.6
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.betterbanking.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * OBPCAData1
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-29T19:03:17.493Z[GMT]")
public class OBPCAData1 {
    @SerializedName("ProductDetails")
    private ProductDetails1 productDetails = null;

    @SerializedName("CreditInterest")
    private CreditInterest1 creditInterest = null;

    @SerializedName("Overdraft")
    private Overdraft1 overdraft = null;

    @SerializedName("OtherFeesCharges")
    private OtherFeesCharges otherFeesCharges = null;

    public OBPCAData1 productDetails(ProductDetails1 productDetails) {
        this.productDetails = productDetails;
        return this;
    }

    /**
     * Get productDetails
     *
     * @return productDetails
     **/
    @Schema(description = "")
    public ProductDetails1 getProductDetails() {
        return productDetails;
    }

    public void setProductDetails(ProductDetails1 productDetails) {
        this.productDetails = productDetails;
    }

    public OBPCAData1 creditInterest(CreditInterest1 creditInterest) {
        this.creditInterest = creditInterest;
        return this;
    }

    /**
     * Get creditInterest
     *
     * @return creditInterest
     **/
    @Schema(description = "")
    public CreditInterest1 getCreditInterest() {
        return creditInterest;
    }

    public void setCreditInterest(CreditInterest1 creditInterest) {
        this.creditInterest = creditInterest;
    }

    public OBPCAData1 overdraft(Overdraft1 overdraft) {
        this.overdraft = overdraft;
        return this;
    }

    /**
     * Get overdraft
     *
     * @return overdraft
     **/
    @Schema(description = "")
    public Overdraft1 getOverdraft() {
        return overdraft;
    }

    public void setOverdraft(Overdraft1 overdraft) {
        this.overdraft = overdraft;
    }

    public OBPCAData1 otherFeesCharges(OtherFeesCharges otherFeesCharges) {
        this.otherFeesCharges = otherFeesCharges;
        return this;
    }

    /**
     * Get otherFeesCharges
     *
     * @return otherFeesCharges
     **/
    @Schema(description = "")
    public OtherFeesCharges getOtherFeesCharges() {
        return otherFeesCharges;
    }

    public void setOtherFeesCharges(OtherFeesCharges otherFeesCharges) {
        this.otherFeesCharges = otherFeesCharges;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OBPCAData1 obPCAData1 = (OBPCAData1) o;
        return Objects.equals(this.productDetails, obPCAData1.productDetails) &&
                Objects.equals(this.creditInterest, obPCAData1.creditInterest) &&
                Objects.equals(this.overdraft, obPCAData1.overdraft) &&
                Objects.equals(this.otherFeesCharges, obPCAData1.otherFeesCharges);
    }

    @Override
    public int hashCode() {
        return Objects.hash(productDetails, creditInterest, overdraft, otherFeesCharges);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OBPCAData1 {\n");

        sb.append("    productDetails: ").append(toIndentedString(productDetails)).append("\n");
        sb.append("    creditInterest: ").append(toIndentedString(creditInterest)).append("\n");
        sb.append("    overdraft: ").append(toIndentedString(overdraft)).append("\n");
        sb.append("    otherFeesCharges: ").append(toIndentedString(otherFeesCharges)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
