/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.6
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.betterbanking.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

/**
 * Period e.g. day, week, month etc. for which the fee/charge is capped
 */
@JsonAdapter(OBPeriod1Code.Adapter.class)
public enum OBPeriod1Code {
    PACT("PACT"),
    PDAY("PDAY"),
    PHYR("PHYR"),
    PMTH("PMTH"),
    PQTR("PQTR"),
    PWEK("PWEK"),
    PYER("PYER");

    private String value;

    OBPeriod1Code(String value) {
        this.value = value;
    }

    public static OBPeriod1Code fromValue(String text) {
        for (OBPeriod1Code b : OBPeriod1Code.values()) {
            if (String.valueOf(b.value).equals(text)) {
                return b;
            }
        }
        return null;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    public static class Adapter extends TypeAdapter<OBPeriod1Code> {
        @Override
        public void write(final JsonWriter jsonWriter, final OBPeriod1Code enumeration) throws IOException {
            jsonWriter.value(enumeration.getValue());
        }

        @Override
        public OBPeriod1Code read(final JsonReader jsonReader) throws IOException {
            String value = jsonReader.nextString();
            return OBPeriod1Code.fromValue(String.valueOf(value));
        }
    }
}
