/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.6
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.betterbanking.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * OBReadDirectDebit2Data
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-29T19:03:17.493Z[GMT]")
public class OBReadDirectDebit2Data {
    @SerializedName("DirectDebit")
    private List<OBReadDirectDebit2DataDirectDebit> directDebit = null;

    public OBReadDirectDebit2Data directDebit(List<OBReadDirectDebit2DataDirectDebit> directDebit) {
        this.directDebit = directDebit;
        return this;
    }

    public OBReadDirectDebit2Data addDirectDebitItem(OBReadDirectDebit2DataDirectDebit directDebitItem) {
        if (this.directDebit == null) {
            this.directDebit = new ArrayList<OBReadDirectDebit2DataDirectDebit>();
        }
        this.directDebit.add(directDebitItem);
        return this;
    }

    /**
     * Get directDebit
     *
     * @return directDebit
     **/
    @Schema(description = "")
    public List<OBReadDirectDebit2DataDirectDebit> getDirectDebit() {
        return directDebit;
    }

    public void setDirectDebit(List<OBReadDirectDebit2DataDirectDebit> directDebit) {
        this.directDebit = directDebit;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OBReadDirectDebit2Data obReadDirectDebit2Data = (OBReadDirectDebit2Data) o;
        return Objects.equals(this.directDebit, obReadDirectDebit2Data.directDebit);
    }

    @Override
    public int hashCode() {
        return Objects.hash(directDebit);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OBReadDirectDebit2Data {\n");

        sb.append("    directDebit: ").append(toIndentedString(directDebit)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
