/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.6
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.betterbanking.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * OBReadConsent1
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-29T19:03:17.493Z[GMT]")
public class OBReadConsent1 {
    @SerializedName("Data")
    private OBReadConsent1Data data = null;

    @SerializedName("Risk")
    private OBRisk2 risk = null;

    public OBReadConsent1 data(OBReadConsent1Data data) {
        this.data = data;
        return this;
    }

    /**
     * Get data
     *
     * @return data
     **/
    @Schema(required = true, description = "")
    public OBReadConsent1Data getData() {
        return data;
    }

    public void setData(OBReadConsent1Data data) {
        this.data = data;
    }

    public OBReadConsent1 risk(OBRisk2 risk) {
        this.risk = risk;
        return this;
    }

    /**
     * Get risk
     *
     * @return risk
     **/
    @Schema(required = true, description = "")
    public OBRisk2 getRisk() {
        return risk;
    }

    public void setRisk(OBRisk2 risk) {
        this.risk = risk;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OBReadConsent1 obReadConsent1 = (OBReadConsent1) o;
        return Objects.equals(this.data, obReadConsent1.data) &&
                Objects.equals(this.risk, obReadConsent1.risk);
    }

    @Override
    public int hashCode() {
        return Objects.hash(data, risk);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OBReadConsent1 {\n");

        sb.append("    data: ").append(toIndentedString(data)).append("\n");
        sb.append("    risk: ").append(toIndentedString(risk)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
