/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.6
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.betterbanking.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * OBReadOffer1Data
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-29T19:03:17.493Z[GMT]")
public class OBReadOffer1Data {
    @SerializedName("Offer")
    private List<OBReadOffer1DataOffer> offer = null;

    public OBReadOffer1Data offer(List<OBReadOffer1DataOffer> offer) {
        this.offer = offer;
        return this;
    }

    public OBReadOffer1Data addOfferItem(OBReadOffer1DataOffer offerItem) {
        if (this.offer == null) {
            this.offer = new ArrayList<OBReadOffer1DataOffer>();
        }
        this.offer.add(offerItem);
        return this;
    }

    /**
     * Get offer
     *
     * @return offer
     **/
    @Schema(description = "")
    public List<OBReadOffer1DataOffer> getOffer() {
        return offer;
    }

    public void setOffer(List<OBReadOffer1DataOffer> offer) {
        this.offer = offer;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OBReadOffer1Data obReadOffer1Data = (OBReadOffer1Data) o;
        return Objects.equals(this.offer, obReadOffer1Data.offer);
    }

    @Override
    public int hashCode() {
        return Objects.hash(offer);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OBReadOffer1Data {\n");

        sb.append("    offer: ").append(toIndentedString(offer)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
