/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.6
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.betterbanking.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Aligning with the read write specs structure.
 */
@Schema(description = "Aligning with the read write specs structure.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-29T19:03:17.493Z[GMT]")
public class OBReadProduct2Data {
    @SerializedName("Product")
    private List<OBReadProduct2DataProduct> product = null;

    public OBReadProduct2Data product(List<OBReadProduct2DataProduct> product) {
        this.product = product;
        return this;
    }

    public OBReadProduct2Data addProductItem(OBReadProduct2DataProduct productItem) {
        if (this.product == null) {
            this.product = new ArrayList<OBReadProduct2DataProduct>();
        }
        this.product.add(productItem);
        return this;
    }

    /**
     * Get product
     *
     * @return product
     **/
    @Schema(description = "")
    public List<OBReadProduct2DataProduct> getProduct() {
        return product;
    }

    public void setProduct(List<OBReadProduct2DataProduct> product) {
        this.product = product;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OBReadProduct2Data obReadProduct2Data = (OBReadProduct2Data) o;
        return Objects.equals(this.product, obReadProduct2Data.product);
    }

    @Override
    public int hashCode() {
        return Objects.hash(product);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OBReadProduct2Data {\n");

        sb.append("    product: ").append(toIndentedString(product)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
