/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.6
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.betterbanking.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * OBReadStandingOrder6Data
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-29T19:03:17.493Z[GMT]")
public class OBReadStandingOrder6Data {
    @SerializedName("StandingOrder")
    private List<OBStandingOrder6> standingOrder = null;

    public OBReadStandingOrder6Data standingOrder(List<OBStandingOrder6> standingOrder) {
        this.standingOrder = standingOrder;
        return this;
    }

    public OBReadStandingOrder6Data addStandingOrderItem(OBStandingOrder6 standingOrderItem) {
        if (this.standingOrder == null) {
            this.standingOrder = new ArrayList<OBStandingOrder6>();
        }
        this.standingOrder.add(standingOrderItem);
        return this;
    }

    /**
     * Get standingOrder
     *
     * @return standingOrder
     **/
    @Schema(description = "")
    public List<OBStandingOrder6> getStandingOrder() {
        return standingOrder;
    }

    public void setStandingOrder(List<OBStandingOrder6> standingOrder) {
        this.standingOrder = standingOrder;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OBReadStandingOrder6Data obReadStandingOrder6Data = (OBReadStandingOrder6Data) o;
        return Objects.equals(this.standingOrder, obReadStandingOrder6Data.standingOrder);
    }

    @Override
    public int hashCode() {
        return Objects.hash(standingOrder);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OBReadStandingOrder6Data {\n");

        sb.append("    standingOrder: ").append(toIndentedString(standingOrder)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
